### PR TITLE
Fix Bug 21203

### PR DESCRIPTION
**Pull request by dfukagaw28**
https://pear.php.net/bugs/bug.php?id=21203

### CODE REVIEW

**Comment by alecpl** [comment]
We should probably use --INI-- section of the phpt file format instead. Then the if wouldn't be needed, I suppose.

**Comment by ashnazg** [comment]
I don't think stuff in the `--INI--` section can denote version conditions, which this `if` is doing.  I'd say the `if` is necessary in this case.

**Comment by alecpl** [comment]
I don't have PHP 5.6 at hand to check, but I believe that deprecated options in --INI-- section do not throw errors/warnings.

**Comment by dfukagaw28** [comment]
I made another commit to this PR following your suggestion.
Hopefully it may work, however, I am actually not familiar with PHP and I don't understand what the test is for.

I have tested it only against PHP 7.1.5 on a Docker container.

**Pull request merged**
