### PR TITLE
Implement #20938: GPG signing and encryption

### PR DESCRIPTION
**Pull request by cweiske**
What do you think?

### CODE REVIEW

**Comment by cweiske** [comment]
@alecpl: What do you think about this patch?

**Comment by alecpl** [comment]
@cweiske, I was going to review it, but in general I'm not sure this is a good idea. Roundcube already implemented this as a wrapper on Mail_mime. See https://github.com/roundcube/roundcubemail/blob/master/plugins/enigma/lib/enigma_mime_message.php. I'm not saying it's better or complete. I just am not sure encryption should be a part of Mail_mime.

**Comment by cweiske** [comment]
Moving this to a standalone class that extends Mail_Mime would be nice. I'm just not sure if Mail_mime is made for this.

**Comment by alecpl** [comment]
enigma_mime_message already extends Mail_mime, so it's not impossible.

I reviewed your changes. Two main issues:
1. It does not support encryption when saving mail to a file, so is not complete.
2. Crypt_GPG throws exceptions, but Mail_mime does not. I don't know what is a common way of handling such situation in PEAR world.

**Pull request closed without merging**
